pub mod reader;
pub mod scanner;
pub mod parallel_reader;
pub mod schema;
pub mod schema_diff;
pub mod stats;
pub mod profile;
pub use parquet_lens_common::{ParquetLensError, Result};
pub use reader::{ParquetFileInfo, SchemaFieldInfo, open_parquet_file};
pub use scanner::{ParquetFilePath, resolve_paths, scan_directory};
pub use parallel_reader::{DatasetProfile, FileProfile, read_metadata_parallel};
pub use schema::{ColumnSchema, extract_schema};
pub use schema_diff::{SchemaInconsistency, InconsistencyKind, check_schema_consistency};
pub use stats::{ColumnStats, AggregatedColumnStats, RowGroupProfile, UniformityReport, EncodingAnalysis, CompressionAnalysis, read_column_stats, aggregate_column_stats, profile_row_groups, analyze_uniformity, analyze_encodings, analyze_compression};
pub use profile::{ColumnProfileResult, CardinalityEstimate, FrequencyResult, NumericProfile, HistogramBin, StringProfile, TemporalProfile, BooleanProfile, profile_columns, build_histogram};
pub mod quality;
pub use quality::{QualityScore, DatasetQuality, DuplicateReport, score_column, summarize_quality, detect_duplicates};
