pub mod reader;
pub mod scanner;
pub mod parallel_reader;
pub mod schema;
pub mod schema_diff;
pub mod stats;
pub mod profile;
pub use parquet_lens_common::{ParquetLensError, Result};
pub use reader::{ParquetFileInfo, SchemaFieldInfo, open_parquet_file};
pub use scanner::{ParquetFilePath, resolve_paths, scan_directory};
pub use parallel_reader::{DatasetProfile, FileProfile, read_metadata_parallel};
pub use schema::{ColumnSchema, extract_schema};
pub use schema_diff::{SchemaInconsistency, InconsistencyKind, check_schema_consistency};
pub use stats::{ColumnStats, AggregatedColumnStats, RowGroupProfile, UniformityReport, EncodingAnalysis, CompressionAnalysis, read_column_stats, aggregate_column_stats, profile_row_groups, analyze_uniformity, analyze_encodings, analyze_compression};
pub use profile::{ColumnProfileResult, CardinalityEstimate, FrequencyResult, NumericProfile, HistogramBin, StringProfile, TemporalProfile, BooleanProfile, profile_columns, profile_columns_with_timeout, build_histogram};
pub mod quality;
pub mod s3_reader;
pub mod gcs_reader;
pub mod compare;
pub mod stats_ext;
pub mod recommendations;
pub mod export;
pub use quality::{QualityScore, DatasetQuality, DuplicateReport, score_column, summarize_quality, detect_duplicates};
pub use s3_reader::{S3Uri, parse_s3_uri, is_s3_uri, list_s3_parquet, read_s3_parquet_metadata, read_s3_range};
pub use gcs_reader::{GcsUri, parse_gcs_uri, is_gcs_uri, list_gcs_parquet, read_gcs_parquet_metadata};
pub use compare::{ColumnSchemaDiff, DiffStatus, ColumnStatsDiff, DatasetComparison, diff_schemas, diff_stats, compare_datasets};
pub use stats_ext::{PartitionInfo, CorrelationMatrix, StringLengthHist, SortedOrderInfo, PageIndexInfo, BloomFilterInfo, analyze_partitions, compute_correlation, string_length_histogram, detect_sort_order, analyze_page_index, detect_bloom_filters};
pub use recommendations::{EncodingRecommendation, CompressionRecommendation, RowGroupSizeRecommendation, recommend_encodings, recommend_compression, recommend_row_group_size};
pub use export::{print_summary, export_json, export_csv};
pub mod filter;
pub use filter::{Predicate, FilterResult, parse_predicate, filter_count};
pub mod sample;
pub use sample::{SampleConfig, SampledProfile, sample_row_groups};
pub mod repair;
pub mod timeseries;
pub mod nested;
pub mod engine;
pub mod null_patterns;
pub mod baseline;
pub use repair::{RepairSuggestion, detect_repair_suggestions};
pub use timeseries::{TimeSeriesProfile, profile_timeseries};
pub use nested::{NestedColumnProfile, profile_nested_columns};
pub use engine::{EngineInfo, identify_engine};
pub use null_patterns::{NullPatternGroup, analyze_null_patterns};
pub use baseline::{BaselineProfile, BaselineRegression, load_baseline_regressions};
